desc view POC_DBT_PROJECT.UTILS.MY_second_DBT_MODEL

DESC TABLE SNOWFLAKE.TELEMETRY.EVENTS;

EXECUTE DBT PROJECT poc_sf_dbt_project;

SHOW PARAMETERS LIKE 'EVENT_TABLE' IN ACCOUNT;
ALTER ACCOUNT SET EVENT_TABLE = SNOWFLAKE.TELEMETRY.EVENTS;

SHOW DBT PROJECTS;

ALTER DBT PROJECT poc_sf_dbt_project
SET LOG_LEVEL = 'INFO';

ALTER DBT PROJECT poc_sf_dbt_project
SET TRACE_LEVEL = 'ALWAYS';

SELECT *
FROM SNOWFLAKE.TELEMETRY.EVENTS
LIMIT 10;

///////////////////

CREATE EVENT TABLE POC_DBT_PROJECT.UTILS.dbt_event_table;

ALTER DATABASE POC_DBT_PROJECT
SET EVENT_TABLE = POC_DBT_PROJECT.UTILS.dbt_event_table;

SELECT *
FROM POC_DBT_PROJECT.UTILS.dbt_event_table
LIMIT 10;

///


-- Use admin role
USE ROLE ACCOUNTADMIN;

-- Verify dbt project exists
SHOW DBT PROJECTS;

-- Go to the database where the dbt project is deployed
USE DATABASE POC_DBT_PROJECT;

-- Create event table for telemetry
CREATE OR REPLACE EVENT TABLE POC_DBT_PROJECT.UTILS.DBT_EVENTS;

-- Verify event table
SHOW EVENT TABLES;

-- Attach event table to database
ALTER DATABASE POC_DBT_PROJECT SET EVENT_TABLE = POC_DBT_PROJECT.UTILS.DBT_EVENTS;

-- Verify the parameter is set
SHOW PARAMETERS LIKE 'EVENT_TABLE' IN DATABASE POC_DBT_PROJECT;

-- Enable detailed logging on dbt project
ALTER DBT PROJECT POC_DBT_PROJECT.UTILS.poc_sf_dbt_project SET LOG_LEVEL = 'DEBUG';

-- Enable tracing
ALTER DBT PROJECT poc_sf_dbt_project SET TRACE_LEVEL = 'ALWAYS';

-- Run the dbt project
EXECUTE DBT PROJECT poc_sf_dbt_project;

-- Wait a few seconds, then query telemetry logs
SELECT
    TIMESTAMP,
    RECORD_TYPE,
    RESOURCE_ATTRIBUTES,
    VALUE
FROM DBT_EVENTS
ORDER BY TIMESTAMP DESC
LIMIT 20;

/// 

ALTER SCHEMA poc_dbt_project.utils SET LOG_LEVEL = 'INFO';
ALTER SCHEMA poc_dbt_project.utils SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA poc_dbt_project.utils SET METRIC_LEVEL = 'ALL';

show tables in schema poc_dbt_project.utils

SELECT table_name
FROM poc_dbt_project.information_schema.tables
WHERE table_schema = '';


create schema POC_DBT_PROJECT.UTILS_STAGING

select * from DBT_PROJECT_EXECUTION_HISTORY

DESCRIBE DBT PROJECT poc_sf_dbt_project;

--- versions

SHOW VERSIONS IN DBT PROJECT POC_SF_DBT_PROJECT;

-- run specific version
EXECUTE DBT PROJECT POC_SF_DBT_PROJECT
ARGS='run'
VERSION='VERSION$1';

---- from git repo directly without using workspace
CREATE OR REPLACE GIT REPOSITORY my_git_repo
API_INTEGRATION = my_git_integration
ORIGIN = 'https://github.com/<org>/<repo>.git';


GRANT ROLE DBT_CICD_ROLE TO USER SWARAJDESHMUKH;



--- create child task
SELECT CURRENT_ROLE();

GRANT CREATE TASK ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE ACCOUNTADMIN;

CREATE OR REPLACE TASK POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_SUCCESS_TASK
WAREHOUSE = COMPUTE_WH
AFTER POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_TASK_RUNNER
AS 
SELECT 'my_first_dbt_model ran successfully' AS MESSAGE;

ALTER TASK POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_TASK_RUNNER RESUME;

SHOW TASKS LIKE 'MY_FIRST_DBT_MODEL_TASK_RUNNER' IN SCHEMA POC_DBT_PROJECT.UTILS;

GRANT USAGE ON DATABASE POC_DBT_PROJECT TO ROLE ACCOUNTADMIN;

GRANT USAGE ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ACCOUNTADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA POC_DBT_PROJECT.UTILS TO ROLE ACCOUNTADMIN;


GRANT CREATE TABLE ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE <ROLE>;


GRANT USAGE ON DATABASE POC_DBT_PROJECT TO ROLE DBT_CICD_ROLE;

GRANT USAGE ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE DBT_CICD_ROLE;

GRANT CREATE TABLE ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE DBT_CICD_ROLE;

GRANT CREATE VIEW ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE DBT_CICD_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_CICD_ROLE;

SHOW TASKS IN SCHEMA POC_DBT_PROJECT.UTILS;

GRANT ALL PRIVILEGES ON TABLE POC_DBT_PROJECT.UTILS.COMPLETE_RUN 
TO ROLE DBT_CICD_ROLE;

GRANT OWNERSHIP ON VIEW POC_DBT_PROJECT.UTILS.MY_SECOND_DBT_MODEL TO ROLE accountadmin;

selec
create or replace TASK POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_SUCCESS_TASK
WAREHOUSE = COMPUTE_WH
AFTER POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_TASK_RUNNER
AS 
SELECT 'my_first_dbt_model ran successfully' AS MESSAGE;



GRANT ROLE ACCOUNTADMIN TO USER DBT_CICD_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE DBT_CICD_ROLE;

GRANT USAGE ON DBT PROJECT POC_DBT_PROJECT.UTILS.POC_SF_DBT_PROJECT 
TO ROLE DBT_CICD_ROLE;

SHOW TASKS IN SCHEMA POC_DBT_PROJECT.UTILS;

USE ROLE <ROLE_NAME>;

-- Try a simple execute via Snowflake session
EXECUTE dbt project POC_SF_DBT_PROJECT args='run --target dev -s my_first_dbt_model';

SHOW TASKS LIKE 'MY_FIRST_DBT_MODEL_TASK_RUNNER' IN SCHEMA POC_DBT_PROJECT.UTILS;

-- 1. Warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_CICD_ROLE;
GRANT USAGE ON DATABASE POC_DBT_PROJECT TO ROLE DBT_CICD_ROLE;

-- 2. Database & schema access (DBT project)
GRANT USAGE ON DATABASE POC_SF_DBT_PROJECT TO ROLE DBT_CICD_ROLE;
GRANT USAGE ON SCHEMA POC_DBT_PROJECT.RAW_VAULT TO ROLE DBT_CICD_ROLE;

-- 3. Table privileges (for all current and future tables)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA POC_DBT_PROJECT.UTILS TO ROLE DBT_CICD_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA POC_DBT_PROJECT.UTILS TO ROLE DBT_CICD_ROLE;

-- Logged in as an admin who can grant ACCOUNTADMIN
GRANT ROLE ACCOUNTADMIN TO USER DBT_CICD_ROLE;

DESCRIBE DBT PROJECT POC_DBT_PROJECT.UTILS.POC_SF_DBT_PROJECT;

GRANT EXECUTE ON DBT PROJECT POC_DBT_PROJECT.UTILS.POC_SF_DBT_PROJECT TO ROLE DEV_ROLE;

GRANT USAGE ON DBT PROJECT POC_DBT_PROJECT.UTILS.POC_SF_DBT_PROJECT TO ROLE DEV_ROLE;

SELECT CURRENT_ROLE();

SHOW GRANTS TO USER swarajdeshmukh;

-- Logged in as DBT_CICD_ROLE
ALTER TASK POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_TASK_RUNNER
SET OWNER USER SWARAJDESHMUKH;

SHOW GRANTS ON TASK POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_TASK_RUNNER;

USE ROLE DBT_CICD_ROLE;

USE ROLE ACCOUNTADMIN;

ALTER TASK POC_DBT_PROJECT.UTILS.MY_FIRST_DBT_MODEL_TASK_RUNNER
SET OWNER ROLE ACCOUNTADMIN;

SHOW GRANTS ON VIEW POC_DBT_PROJECT.UTILS.MY_SECOND_DBT_MODEL;

ALTER VIEW POC_DBT_PROJECT.UTILS.MY_SECOND_DBT_MODEL
SET OWNER ROLE ACCOUNTADMIN;

SHOW GRANTS ON SCHEMA POC_DBT_PROJECT.UTILS;

GRANT ALL PRIVILEGES ON SCHEMA POC_DBT_PROJECT.UTILS TO ROLE accountadmin;

select * from POC_DBT_PROJECT.UTILS_STAGING.SALES_DATA

GRANT USAGE ON SCHEMA POC_DBT_PROJECT.UTILS_STAGING TO ROLE ACCOUNTADMIN;

GRANT CREATE TABLE ON SCHEMA POC_DBT_PROJECT.UTILS_STAGING TO ROLE ACCOUNTADMIN;
GRANT CREATE VIEW ON SCHEMA POC_DBT_PROJECT.UTILS_STAGING TO ROLE ACCOUNTADMIN;

select * from snowflake.account_usage.query_history

select * from poc_dbt_project.utils.dbt_events

EXECUTE DBT PROJECT my_tester_dbt_project_object_gh_action args='run --target dev'


USE DATABASE POC_DBT_PROJECT;
USE SCHEMA RAW_VAULT;

-- Check if tables exist
SHOW TABLES;

SHOW GRANTS ON SCHEMA POC_DBT_PROJECT.RAW_VAULT;

GRANT SELECT ON TABLE POC_DBT_PROJECT.RAW_VAULT.RAW_CUSTOMERS TO ROLE DBT_CICD_ROLE;
GRANT SELECT ON TABLE POC_DBT_PROJECT.RAW_VAULT.RAW_ORDERS TO ROLE DBT_CICD_ROLE;
